### ISSUE TITLE
body and timeline output don't work, 'patch' included

### ISSUE THREAD

**Issue by maxpunktezahl** [rowingdude/analyzeMFT#142]
If you add
 
elif self.export_format == "body":
            await FileWriters.write_body(list(self.mft_records.values()), self.output_file)
        elif self.export_format == "timeline":
            await FileWriters.write_timeline(list(self.mft_records.values()), self.output_file)

after line 253 in mft_analyzer.py 

the output of timeline and body will work too.
Thank you very much for the great tool!

**Comment by rowingdude** [comment]
If you'd like to make a PR, I'd be happy to merge it so you get credit.

**Comment by maxpunktezahl** [comment]
Thank you so much! Sorry, no time for PR - I am abroad.
