### ISSUE TITLE
Any chance to get a dual licensing?

### ISSUE THREAD

**Issue by Lazza** [rowingdude/analyzeMFT#26]
Hi, I am a MSc student working on a thesis related to NTFS file recovery. I'm planning to write an open source software (GPLv3) in Python which will apply some data recovery techniques. When I found your project I was hoping to be able to add its functionality to my application, in order to focus on the subject of my thesis which is directory tree reconstruction from MFT entries in damaged drives.

However, I can't. That's because the Common Public License is not compatible with the GPL, so I would breach your license in case I used a part of `analyzeMFT` as a library for my GPL software. Is there any chance that you and the few contributors may consider licensing the code also under the GPL?

Thank you very much in advance, and don't worry if the answer is no. I'll understand.

**Comment by dkovar** [comment]
I'd like to help you with this, but getting everyone to agree on it, retroactively and going forward, would be problematic.

Can I somehow grant you an exemption?

**Comment by Lazza** [comment]
Thank you for the answer. I think even an exemption would require agreement from other contributors. Anyways, I was able to implement the parsing of the attributes I need for my purpose: `$FILE_NAME`, `$STANDARD_INFORMATION` and so on. Doing it myself was good because I learnt more about the structure of an MFT entry and it will consitute good material for writing the thesis.

Thank you for your time devoted to develop open source software.
