### ISSUE TITLE
Trouble getting excel friendly

### ISSUE THREAD

**Issue by DigiAngel** [rowingdude/analyzeMFT#27]
Not sure how this is supposed to work, but I've been trying to get an excel friendly timestamp.  Here's what I've tried:

python analyzeMFT.py -l -p -f ~/Forensics/cases/macbook/mft.bin -e -c /home/Forensics/cases/macbook/excel.csv

python analyzeMFT.py -l -p -f ~/Forensics/cases/macbook/mft.bin -e /home/Forensics/cases/macbook/excel.csv

python analyzeMFT.py -l -p -f ~/Forensics/cases/macbook/mft.bin -e -o /home/Forensics/cases/macbook/excel.csv

Almost all of which give me:
2014-08-01|12:31:44.735449|TZ|

Is there something I'm missing?  Thank you.

**Comment by aceplt** [comment]
HI need help passing variable in a python script calling a subprocess. "subprocess.call(shlex.split('./analyzeMFT.py -f filename.mft'] -o ['filename.csv']'))"
