### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by josephernest** [rowingdude/analyzeMFT#49]
I `git clone`d and installed analyzeMFT, but I don't know how to test it, for example, on my `D:\`. Can you give an example (for Windows) about how to analyze the MFT of an exisiting drive?

Thanks.

**Comment by dkovar** [comment]
Greetings,

You need to extract the $MFT from the file system first and then point analyzeMFT at it.

-David

**Comment by josephernest** [comment]
Thanks. How to extract the MFT of my NTFS `D:\` with Windows?

**Comment by aei4n6** [comment]
Hello,

Check out this article (
https://whereismydata.wordpress.com/2009/06/05/forensics-what-is-the-mft/).
There are plenty of Forensics articles out there that can help guide and
teach, but my recommendation would be to research the $MFT file itself so
that you can understand what it is and what its purpose is and THEN extract
and rip it.

​
--
Devon Ackerman
​​

GCFA, GCFE, CFCE, CDFC, CICP, CCE
<http://linkedin.com/devonackerman>Definitive DFIR Compendium Project
<http://www.aboutdfir.com>
Ransomware Research Project
<https://goo.gl/b9R8DE>
APT Groups & Operations
<https://goo.gl/QEayyo>
​
​
<https://goo.gl/QEayyo>[linkedin]
<https://www.linkedin.com/in/devonackerman> | [twitter]
<https://twitter.com/aei4n6>​

**Comment by josephernest** [comment]
Thanks @aei4n6 I read a few related articles. But I can imagine there exists a ready-to-use tool on Windows that can extract/display the $MFT file?

**Comment by aei4n6** [comment]
My humble recommendation would be something like AccessData's FTK Imager to
expose and scrape out the system/hidden $MFT file itself.

​
--
Devon Ackerman
​​

GCFA, GCFE, CFCE, CDFC, CICP, CCE
<http://linkedin.com/devonackerman>Definitive DFIR Compendium Project
<http://www.aboutdfir.com>
Ransomware Research Project
<https://goo.gl/b9R8DE>
APT Groups & Operations
<https://goo.gl/QEayyo>
​
​
<https://goo.gl/QEayyo>[linkedin]
<https://www.linkedin.com/in/devonackerman> | [twitter]
<https://twitter.com/aboutdfir>

**Comment by rowingdude** [comment]
I am going to close this as I have included a comprehensive USAGE.md in the directory.
