### ISSUE TITLE
python2

### ISSUE THREAD

**Issue by patatetom** [rowingdude/analyzeMFT#50]
hi,

python2 and python3 may be installed together...

```patch
diff --git a/analyzeMFT.py b/analyzeMFT.py
index dceaae7..0d21be5 100755
--- a/analyzeMFT.py
+++ b/analyzeMFT.py
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/python2
 
 try:
     from analyzemft import mftsession
```

```bash
# pip2 install analyzeMFT
Collecting analyzeMFT
  Using cached analyzeMFT-2.0.19.tar.gz
Installing collected packages: analyzeMFT
  Running setup.py install for analyzeMFT ... done
Successfully installed analyzeMFT-2.0.19

# pip3 install analyzeMFT
Collecting analyzeMFT
  Using cached analyzeMFT-2.0.19.tar.gz
Installing collected packages: analyzeMFT
  Running setup.py install for analyzeMFT ... done
Successfully installed analyzeMFT-2.0.19

# pip2 check
No broken requirements found.

# pip3 check
No broken requirements found.

# python2 /usr/bin/analyzeMFT.py 
-f <filename> required.

# python3 /usr/bin/analyzeMFT.py 
Traceback (most recent call last):
  File "/usr/bin/analyzeMFT.py", line 6, in <module>
    from .analyzemft import mftsession
ModuleNotFoundError: No module named '__main__.analyzemft'; '__main__' is not a package
```

**Comment by williballenthin** [comment]
analyzeMFT is written in python2 and does not support python3. there are a number of python3 incompatibilities (relative imports, print statements, etc.) that would need to be fixed even before regression testing happens. while it appears to install ok via pip3, you should not attempt to use it.

**Comment by eddsalkield** [comment]
I have forked the project and [converted it to python3](https://github.com/eddsalkield/analyzeMFT3). This should work for your use case.

**Comment by kovar-ursa** [comment]
Thank you both. It would probably make sense to make that fork the "official" version.

**Comment by eddsalkield** [comment]
You can find it packaged at the [PyPi](https://pypi.org), as [analyzeMFT3](https://pypi.org/project/analyzeMFT3).

**Comment by joachimmetz** [comment]
@dkovar what is the status of this? are you planning to merge the python3 changes back into this git repo? or has the "official" repo for analyzeMFT changed?

**Comment by joachimmetz** [comment]
@eddsalkield since analyzeMFT3 has no separate issue tracker

```
python3 -V
Python 3.7.6

PYTHONPATH=analyzeMFT3 python3 analyzeMFT3/analyzeMFT.py -f MFT.bin -b bodyfile --bodyfull -d
...
Traceback (most recent call last):
  File "analyzeMFT3/analyzeMFT.py", line 12, in <module>
    session.process_mft_file()
  File "analyzeMFT3/analyzemft/mftsession.py", line 189, in process_mft_file
    self.build_filepaths()
  File "analyzeMFT3/analyzemft/mftsession.py", line 281, in build_filepaths
    record = mft.parse_record(raw_record, self.options)
  File "analyzeMFT3/analyzemft/mft.py", line 70, in parse_record
    atr_record = decode_atr_header(raw_record[read_ptr:])
  File "analyzeMFT3/analyzemft/mft.py", line 598, in decode_atr_header
    d = {'type': struct.unpack("<L", s[:4])[0]}
TypeError: a bytes-like object is required, not 'str'
```

**Comment by dkovar** [comment]
I have not touched this project in many years and, alas, have no plans for it. I'm happy to turn it over to someone else if there is interest.

**Comment by joachimmetz** [comment]
@eddsalkield are you planning to continue the python 3 version of this project?

@dkovar it is unfortunate that this project has been abandoned, can you add some note to the README that this project is no longer actively maintained?

**Comment by eddsalkield** [comment]
Unfortunately I do not intend to continue the python3 version of the project, as I no longer use this utility.

**Comment by joachimmetz** [comment]
Ack, as requested before, mention something about the unmaintained status in the readme file.

**Comment by kovar-ursa** [comment]
From the README.

===========
STATUS

This project was my passion and my vehicle for exploring digital forensics for many years as well as a means for giving back to a
community that gave me so much.

Unfortunately, I am no doing forensics on Windows filesystems and am not contributing to this project anymore. If someone else
wishes to adopt it, please let me know.

-David (02/02/2020)
===========
Analyze MFT
===========

David Kovar
CEO, URSA Inc.
Email: dkovar@ursasecure.com
Cell: 650-278-1774

**Comment by joachimmetz** [comment]
@kovar-ursa, ack thx, for updating it, I was mainly referring to @eddsalkield his update which does not indicate analyzeMFT3 is not maintained either https://github.com/eddsalkield/analyzeMFT3/blob/master/README.txt

**Comment by eddsalkield** [comment]
Thanks for the mention.  I have modified the README to make it clear that my fork is unmaintained.

**Comment by rowingdude** [comment]
Version 2.1 on is compliant with Python 3 and uses Python 3.12 as its base.
