### ISSUE TITLE
Option to supress csv header

### ISSUE THREAD

**Issue by tbi360** [rowingdude/analyzeMFT#60]
I use this tool a lot and I plug it into other scripts which do not require header function. would it be possible to have an option to suppress this?

Many thanks

**Comment by dkovar** [comment]
Alas, I've not touched the code in three years and am unlikely to add this. That said, it should be quite simple and I'll see if I can get to it. 

In the mean time, you could pipe the output through tail:

tail -n +2

(sed and awk can do something similar)

I'm glad you are still finding this useful.
