### ISSUE TITLE
PyPI releases + git tags

### ISSUE THREAD

**Issue by micwoj92** [rowingdude/analyzeMFT#62]
Hello @rowingdude ,
Using git tags would make it easier to package this software.
Currently distros package old versions of this software (2.x) with the exception of openbsd ports where commit 16d12822563cd5cae8675788134ac0ff6e9f5c01 was picked:
https://github.com/openbsd/ports/blob/master/sysutils/py-analyzemft/Makefile#L7#61 

@dkovar You are still maintainer on PYPI. Have you spoken with @rowingdude regarding packaging the software there?

**Comment by rowingdude** [comment]
Thanks for pointing this out, I've reached out to get this updated. Thank you and I'll be releasing several updates and several fixes in a couple of weeks.

**Comment by micwoj92** [comment]
I don't think it's completed. There are no new tags and pypi still has old version. https://pypi.org/project/analyzeMFT/

**Comment by rowingdude** [comment]
I haven’t published it to pypi yet. Thanks for the reminder
