### ISSUE TITLE
Error in Line 76 -CSV

### ISSUE THREAD

**Issue by BroBio200** [rowingdude/analyzeMFT#85]
Hi, 
i installed with Pip3 the analyzedMFT Projekt, 
after i want to analyze some data, i got errors like that:

Error in line 76, close_files for self.file_csv_time

my command is python3 analyzeMFT.py /path/inputfile --csv-filename output.csv

With pip3 show anaöyzedMFT:
Version:2.1.1.2

Best Regards

**Comment by rowingdude** [comment]
You're right! I made a slight blunder when moving things into this new class hierarchy. I have corrected the issue and am putting the patch up in version 2.1.1.2, sorry for the troubles.
